caf_co_max – Caffeine
caf_co_max Module Procedure
24 statements
Source File
module procedure caf_co_max module module subroutine caf_co_max(a, result_image, stat, errmsg) Interface →
Arguments
Type Intent Optional Attributes Name
type(*), intent(inout), contiguous, target :: a(..)
integer, intent(in), optional target :: result_image
integer, intent(out), optional target :: stat
character(len=*), intent(inout), optional target :: errmsg
Calls
Called by
Contents
None
Call graph
caf_co_max calls caf_c_numeric_type, get_c_ptr, caf_c_is_f_string, get_c_ptr_character, caf_c_co_max, caf_error_stop, optional_value, caf_co_reduce, caf_co_max
caf_co_reduce calls caf_co_reduce, get_c_ptr, caf_c_is_f_string, get_c_ptr_character, caf_error_stop, optional_value, assert, caf_c_elem_len, caf_c_same_cfi_type, caf_c_co_reduce
assert calls assert, caf_error_stop