prif_co_max – Caffeine
prif_co_max Module Procedure
24 statements
Source File
module procedure prif_co_max module module subroutine prif_co_max(a, result_image, stat, errmsg, errmsg_alloc) Interface →
Arguments
Type Intent Optional Attributes Name
type(*), intent(inout), contiguous, target :: a(..)
integer(kind=c_int), intent(in), optional :: result_image
integer(kind=c_int), intent(out), optional :: stat
character(len=*), intent(inout), optional :: errmsg
character(len=:), intent(inout), optional allocatable :: errmsg_alloc
Calls
Called by
Contents
None
Call graph
prif_co_max calls caf_co_max, caf_is_f_string, prif_co_reduce, optional_value, get_c_ptr, caf_numeric_type, get_c_ptr_character, prif_error_stop, prif_co_max
prif_co_reduce calls prif_co_reduce, caf_is_f_string, optional_value, get_c_ptr, get_c_ptr_character, prif_error_stop, caf_same_cfi_type, caf_co_reduce, caf_elem_len, assert
prif_error_stop calls prif_error_stop, prif_error_stop_character, prif_error_stop_integer
prif_error_stop_character calls f_c_string
assert calls assert, prif_error_stop