prif_deallocate_coarray – Caffeine
prif_deallocate_coarray Interface
791 statements
Source File
interface
Calls
public module module subroutine prif_deallocate_coarray(coarray_handles, stat, errmsg, errmsg_alloc) Implementation →
Arguments
Type Intent Optional Attributes Name
type(prif_coarray_handle), intent(in) :: coarray_handles(:)
integer(kind=c_int), intent(out), optional :: stat
character(len=*), intent(inout), optional :: errmsg
character(len=:), intent(inout), optional allocatable :: errmsg_alloc
Call graph
prif_deallocate_coarray calls prif_deallocate_coarray, caf_deallocate, caf_this_image, remove_from_team_list, prif_sync_all, prif_error_stop
prif_sync_all calls prif_sync_all, caf_sync_all
prif_error_stop calls prif_error_stop, prif_error_stop_character, prif_error_stop_integer
prif_error_stop_character calls f_c_string