name: Build

on:
  push:
    paths-ignore: &paths_ignore
      - 'docs/**'
      - '**.txt'
      - '**.md'
  pull_request:
    paths-ignore: *paths_ignore
  workflow_dispatch:
    inputs:
      fflags:
        description: 'Additional FFLAGS'
        type: string
        required: false
      cflags:
        description: 'Additional CFLAGS'
        type: string
        required: false
      install_args:
        description: 'Additional install/configure args'
        type: string
        required: false
      julienne_args:
        description: 'Additional Julienne driver args'
        type: string
        required: false
      env_vars:
        description: 'Environment vars: k1=v1 k2=v2'
        type: string
        default: ''
        required: false

concurrency:
  # De-duplicate concurrent workflow runs on the same branch/ref
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}-${{ ( github.event_name == 'workflow_dispatch' && github.run_id ) || 'auto' }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

defaults:
  run:
    shell: bash --noprofile --norc -e -x -o pipefail {0}

jobs:
  setup: # establish default configuration values, independent of repo/org
    name: Setup
    runs-on: ubuntu-latest
    outputs: 
      # The LLVM Flang version on Homebrew : https://formulae.brew.sh/formula/flang
      BREW_FLANG_VERSION: ${{ steps.vars.outputs.BREW_FLANG_VERSION }}
    steps:
      - name: Set default configuration variables
        id: vars
        run: echo "BREW_FLANG_VERSION=23" >> $GITHUB_OUTPUT

  build:
    name: ${{ matrix.compiler }}-${{ matrix.version || needs.setup.outputs.BREW_FLANG_VERSION }} ${{ ( matrix.network != 'smp' && matrix.network ) || '' }} (${{ matrix.os }}) ${{ matrix.label }}
    needs: setup
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-14, macos-15, macos-15-intel, macos-26, macos-26-intel, ubuntu-24.04 ]
        compiler: [ gfortran ]
        version: [ 13, 14, 15, 16 ]
        network: [ smp ]

        exclude:

          # Homebrew removed Intel bottles for gcc@16
          - os: macos-15-intel
            version: 16
          - os: macos-26-intel
            version: 16

        include:

        # --- Other selected GFortran+Linux combos ---
          - os: ubuntu-26.04
            compiler: gfortran
            version: 16
          - os: ubuntu-26.04-arm
            compiler: gfortran
            version: 16
          - os: ubuntu-24.04-arm
            compiler: gfortran
            version: 16
          
        # --- flang coverage ---
          - os: macos-15
            compiler: flang
            brew_via_install: 1
          - os: macos-26
            compiler: flang
            brew_via_install: 1
          # No Homebrew bottle for Intel, use MacPorts instead
          - os: macos-15-intel
            compiler: flang
            version: 23
            macports: 1
          - os: macos-26-intel
            compiler: flang
            version: 23
            macports: 1

          - os: ubuntu-24.04
            compiler: flang
            label: Homebrew
            brew_via_install: 1

          - os: ubuntu-26.04-arm
            label: Homebrew
            compiler: flang
            brew_via_install: 1

          # https://hub.docker.com/r/snowstep/llvm/tags
          - os: ubuntu-24.04
            compiler: flang
            version: latest
            container: snowstep/llvm:ubuntu-24.04-latest
            #container: snowstep/llvm:debian-12-latest

          # https://hub.docker.com/r/phhargrove/llvm-flang/tags
          - os: ubuntu-24.04-arm
            compiler: flang
            version: 23
            container: phhargrove/llvm-flang:23.1.0-latest-arm64

          - os: ubuntu-24.04
            compiler: flang
            version: 23
            container: phhargrove/llvm-flang:23.1.0-latest
          - os: ubuntu-24.04
            compiler: flang
            version: 22
            container: phhargrove/llvm-flang:22.1.3-latest
          - os: ubuntu-24.04
            compiler: flang
            version: 21
            container: phhargrove/llvm-flang:21.1.0-latest
          - os: ubuntu-24.04
            compiler: flang
            version: 20
            container: phhargrove/llvm-flang:20.1.0-latest
          - os: ubuntu-24.04
            compiler: flang
            version: 19
            container: phhargrove/llvm-flang:19.1.1-latest

        # --- lfortran coverage ---

          # https://github.com/lfortran/lfortran/pkgs/container/lfortran
          - os: ubuntu-22.04
            compiler: lfortran
            version: latest
            container: ghcr.io/lfortran/lfortran:latest

          - os: ubuntu-22.04
            compiler: lfortran
            version: 0.66
            container: ghcr.io/lfortran/lfortran:v0.66.0

          - os: ubuntu-22.04
            compiler: lfortran
            version: 0.65
            container: ghcr.io/lfortran/lfortran:v0.65.0

          - os: ubuntu-22.04
            compiler: lfortran
            version: 0.64
            container: ghcr.io/lfortran/lfortran:v0.64.0

          - os: ubuntu-22.04
            compiler: lfortran
            version: 0.63
            container: ghcr.io/lfortran/lfortran:v0.63.0

        # --- OPT coverage ---
          - os: ubuntu-24.04
            compiler: flang
            version: 23
            label: OPT
            CONFIGURE_ARGS: --disable-debug
            container: phhargrove/llvm-flang:23.1.0-latest
          - os: ubuntu-22.04
            compiler: lfortran
            version: 0.66
            label: OPT
            CONFIGURE_ARGS: --disable-debug
            container: ghcr.io/lfortran/lfortran:v0.66.0

        # --- PRIF-old coverage ---
          - os: ubuntu-24.04
            compiler: flang
            version: 21
            label: PRIF-0.5
            FFLAGS: -DFORCE_PRIF_0_5
            container: phhargrove/llvm-flang:21.1.0-latest
          - os: ubuntu-24.04
            compiler: flang
            version: 21
            label: PRIF-0.6
            FFLAGS: -DFORCE_PRIF_0_6
            container: phhargrove/llvm-flang:21.1.0-latest
          - os: ubuntu-24.04
            compiler: flang
            version: 21
            label: PRIF-0.7
            FFLAGS: -DFORCE_PRIF_0_7
            container: phhargrove/llvm-flang:21.1.0-latest

        # --- udp coverage for selected configs ---
          - os: macos-26
            compiler: gfortran
            version: 16
            network: udp
          - os: macos-15
            compiler: gfortran
            version: 14
            network: udp

          - os: ubuntu-24.04
            compiler: gfortran
            version: 16
            network: udp
          - os: ubuntu-24.04
            compiler: gfortran
            version: 14
            network: udp

          # No Homebrew bottle for Intel, use MacPorts instead
          - os: macos-15-intel
            compiler: flang
            version: 23
            macports: 1
            network: udp
          - os: macos-26-intel
            compiler: flang
            version: 23
            macports: 1
            network: udp

          - os: macos-15
            compiler: flang
            network: udp
            label: FPM-0.10
            FPM_VERSION: 0.10.0
          - os: macos-26
            compiler: flang
            network: udp

          - os: ubuntu-24.04
            compiler: flang
            version: 20
            network: udp
            container: phhargrove/llvm-flang:20.1.0-latest
          - os: ubuntu-24.04
            compiler: flang
            version: 21
            network: udp
            container: phhargrove/llvm-flang:21.1.0-latest
          - os: ubuntu-24.04
            compiler: flang
            version: 22
            network: udp
            container: phhargrove/llvm-flang:22.1.0-latest
          - os: ubuntu-24.04-arm
            compiler: flang
            network: udp
            version: 23
            container: phhargrove/llvm-flang:23.1.0-latest-arm64
          - os: ubuntu-24.04
            compiler: flang
            version: 23
            network: udp
            container: phhargrove/llvm-flang:23.1.0-latest
            label: FPM-0.10
            FPM_VERSION: 0.10.0
          - os: ubuntu-24.04
            compiler: flang
            version: latest
            network: udp
            container: snowstep/llvm:ubuntu-24.04-latest
            #container: snowstep/llvm:debian-12-latest

    container:
      image: ${{ matrix.container }}
      options: --shm-size=2gb

    env:
      COMPILER_VERSION: ${{ matrix.version || needs.setup.outputs.BREW_FLANG_VERSION }}
      FFLAGS: ${{ matrix.FFLAGS }} ${{ inputs.fflags }}
      CFLAGS: ${{ matrix.CFLAGS }} ${{ inputs.cflags }}
      FPM_VERSION: ${{ matrix.FPM_VERSION || '0.13.0' }}
      NETWORK_ARG: ${{ matrix.network && format('--network={0}',matrix.network) || '' }}
      CURL_OPTIONS: -L --retry 10 --retry-all-errors --fail 
      CONFIGURE_ARGS: --prefix=install --enable-rpath --enable-debug --verbose ${{ matrix.CONFIGURE_ARGS }}
      GASNET_SPAWN_VERBOSE: 1
      GASNET_SPAWNFN: L
      GASNET_MASTERIP: 127.0.0.1
      CAF_IMAGES: 8
      BREW_WARNING_FILTER: 's/^[[:punct:]]*warning[[:punct:]]*(You are using macOS on Intel)/warn: \1/i'

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    ##########################################################################
    # Establish Dependencies

    - name: Install Ubuntu Container Dependencies
      if: ${{ contains(matrix.os, 'ubuntu') && matrix.container != '' && !contains(matrix.container, 'phhargrove') }}
      run: |
        apt update
        apt install -y build-essential pkg-config make git curl

    - name: Install Ubuntu Native Dependencies
      if: ${{ contains(matrix.os, 'ubuntu') && matrix.container == '' && !matrix.brew_via_install }}
      run: |
        sudo apt update
        sudo apt install -y build-essential pkg-config make
        if [[ ${COMPILER_VERSION} -lt 15 ]] || type -p gfortran-${COMPILER_VERSION} ; then
          sudo apt install -y gfortran-${COMPILER_VERSION} g++-${COMPILER_VERSION}
        else
          curl $CURL_OPTIONS https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh -o install-homebrew.sh
          chmod +x install-homebrew.sh
          env CI=1 ./install-homebrew.sh
          HOMEBREW_PREFIX="/home/linuxbrew/.linuxbrew"
          ${HOMEBREW_PREFIX}/bin/brew install -v gcc@${COMPILER_VERSION} binutils
          ls -al ${HOMEBREW_PREFIX}/bin
          echo "PATH=${HOMEBREW_PREFIX}/bin:${PATH}" >> "$GITHUB_ENV"
          : Homebrew GCC@15 needs binutils 2.44+
          HOMEBREW_BINUTILS=$(ls -d ${HOMEBREW_PREFIX}/Cellar/binutils/2.*/bin )
          ls -al ${HOMEBREW_BINUTILS}
          echo "FFLAGS=${FFLAGS:+"$FFLAGS" }-B ${HOMEBREW_BINUTILS}" >> "$GITHUB_ENV"
          echo "CFLAGS=${CFLAGS:+"$CFLAGS" }-B ${HOMEBREW_BINUTILS}" >> "$GITHUB_ENV"
          echo "CXXFLAGS=${CXXFLAGS:+"$CXXFLAGS" }-B ${HOMEBREW_BINUTILS}" >> "$GITHUB_ENV"
          echo "LDFLAGS=${LDFLAGS:+"$LDFLAGS" }-B ${HOMEBREW_BINUTILS}" >> "$GITHUB_ENV"
        fi

    - name: Fix macOS Homebrew Configuration
      if: ${{ contains(matrix.os, 'macos') && !matrix.macports }}
      run: |
        # silence Homebrew tap trust warnings:
        (set +e ; brew untap -f aws/tap hashicorp/tap 2>&1 | perl -pe 's/#*.warning./warn: /' ; brew trust azure/bicep )
        # set some Homebrew knobs to accelerate installation
        # but only when we are not simulating the user environment brew-via-install workflow
        if [[ -z "${{ matrix.brew_via_install }}" ]] ; then
          echo HOMEBREW_NO_ANALYTICS=1 >> "$GITHUB_ENV"
          echo HOMEBREW_NO_AUTO_UPDATE=1 >> "$GITHUB_ENV"
          echo HOMEBREW_NO_GITHUB_API=1 >> "$GITHUB_ENV"
          echo HOMEBREW_NO_INSTALL_CLEANUP=1 >> "$GITHUB_ENV"
        fi

    - name: Setup Macports
      if: matrix.macports
      uses: melusina-org/setup-macports@v1

    - name: Install macOS Dependencies (Homebrew)
      if: ${{ contains(matrix.os, 'macos') && !matrix.macports && !matrix.brew_via_install }}
      run: |
        brew update
        # fpm binary distribution for macOS requires gfortran shared libraries from gcc@12
        brew install gcc@12 \
            2>&1 | perl -pe "$BREW_WARNING_FILTER" ; test ${PIPESTATUS[0]} = 0
        if [[ ${{ matrix.compiler }} == 'gfortran' && ${COMPILER_VERSION} -gt 15 ]] ; then
          brew install gcc@${COMPILER_VERSION} \
            2>&1 | perl -pe "$BREW_WARNING_FILTER" ; test ${PIPESTATUS[0]} = 0
        fi

    - name: Install macOS Dependencies (Macports)
      if: matrix.macports
      run: |
        #sudo port -v selfupdate
        if [[ ${{ matrix.compiler }} == 'gfortran' && ${COMPILER_VERSION} -gt 15 ]] ; then
          sudo port -v install gcc${COMPILER_VERSION}
        fi
        # Append Macports dynamic library directory
        echo "DYLD_FALLBACK_LIBRARY_PATH=/opt/local/lib/libgcc/:$DYLD_FALLBACK_LIBRARY_PATH" >> "$GITHUB_ENV"

    - name: Install LLVM flang on macOS (Homebrew)
      if: ${{ contains(matrix.os, 'macos') && matrix.compiler == 'flang' && !matrix.macports && !matrix.brew_via_install }}
      run: |
        brew install llvm@${COMPILER_VERSION} flang \
            2>&1 | perl -pe "$BREW_WARNING_FILTER" ; test ${PIPESTATUS[0]} = 0
          perl -pe "$BREW_WARNING_FILTER" ; test ${PIPESTATUS[0]} = 0
        # Prepend homebrew clang to PATH:
        echo "PATH=$(brew --prefix)/opt/llvm/bin:${PATH}" >> "$GITHUB_ENV"

    - name: Install LLVM flang on macOS (Macports)
      if: ${{ matrix.compiler == 'flang' && matrix.macports }}
      run: |
        sudo port -v install flang-${COMPILER_VERSION}
        sudo ln -sf /opt/local/bin/flang-mp-${COMPILER_VERSION} /opt/local/bin/flang
        sudo ln -sf /opt/local/bin/flang-mp-${COMPILER_VERSION} /opt/local/bin/flang-new
        sudo ln -sf /opt/local/bin/clang-mp-${COMPILER_VERSION} /opt/local/bin/clang
        sudo ln -sf /opt/local/bin/clang++-mp-${COMPILER_VERSION} /opt/local/bin/clang++
        # Prepend Macports clang to PATH:
        echo "PATH=/opt/local/bin:${PATH}" >> "$GITHUB_ENV"

